### PR TITLE
adding discuss and act button into the summary dialog

### PR DESCRIPTION
**Pull request by polatengin**
# Pull Request

Relevant Issue(s): #449 

## Description

Adding `Discuss and Act` button into the `Retrospective Summary` dialog to change the board template to the template that needs to be discussed.

## Bug or Feature?

- [ ] Bug fix
- [x] New feature

## Fundamentals

- [x] I have read the [**CONTRIBUTING**](https://github.com/microsoft/vsts-extension-retrospectives/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] I have updated any relevant documentation accordingly.
- [x] I have included an update blurb (50 words or less) at the top of `CHANGELOG.md`,
    to be included with the next release.
  - [x] I have included a link to this PR in that blurb.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

## Accessibility

- [x] I have tested my changes on both light and dark themes.
- [ ] I have tested my changes on both mobile and desktop views, when needed.
- [ ] I have included image descriptions and aria-labels where I can.

## Screenshots and Logs

N/A

### CODE REVIEW

**Comment by SharkeyPaul** [comment]
Hi, 

Why have you done this? Making new Retro Boards anonymous by default? 

What is the justification for this? It should be for each DEV to decide if their feedback is anonymous when they are creating items. Not a complete Board default which is frankly ridiculous.

This is affecting MILLIONS of people who will now have to remember EVERY time they create a new Retro Board to UNTICK what you have implemented!! 

[making board anonymous by default](https://github.com/microsoft/vsts-extension-retrospectives/pull/462/commits/f182f47679ed9432a8a72966e61c9da030ee2388)

**Comment by DMSuit** [comment]
Hi,
I agree with SharkeyPaul - showing the name of who provides the feedback on the Retrospective should be the default.  Users should need to actively say 'No' by checking the box to keep the submitter anonymous.

_NEED TEAM ASSESSMENT INFO_ - I can find nothing in any of the release notes showing me where the survey responses go or how to pull the information. I've checked everywhere I know to look.  I cannot effectively use or promote use of a feature if I do not know how it works and where the feedback is captured.  It would be helpful if the 'What's New' notes had a link to show or outline how to use new features.

Thanks in advance for any assistance in determining how to use this feature and report the results.

**Comment by polatengin** [comment]
@dstoddar can I ask you to chime in here, please?

I know you replied to a similar question in https://github.com/microsoft/vsts-extension-retrospectives/discussions/472

I think the next "big" feature would be the global config to store the "defaults" of selections. so, it'd be relatively easier to make sure the retro sessions will have similar config applied.

What you think?

**Comment by SharkeyPaul** [comment]
Hi,

Making a Board anonymous will not ensure you get feedback from everybody. 

This smacks of #Wokism if I am brutally honest. A detestable concept. 

If you want to streamline the creation of the ADO Retro Boards then let Team members who feel "psychologically unsafe" tick a box when providing their feedback that allows them to remain anonymous.

I am extremely concerned that with this change you are permitting the minority to drive the agenda. 

Please reverse out your change and treat the vast majority of the ADO Community with some respect.

Thank you,

Paul Sharkey.

**Comment by dstoddar** [comment]
@SharkeyPaul ,

Are you available for a phone call? You are raising some great points and I want to understand your concerns more fully so we can  collaborate on a long term solution.

Quick question on your comment about allowing minority to drive the agenda. Voting is anonymous and has always been that way. Does your team utilize votes to determine follow-up actions?

Thank you

Damon

**Comment by SharkeyPaul** [comment]
Cheers Damon. 

Appreciate the offer but I'm feeling a tad psychologically unsafe ;-)

Paul.

**Comment by dstoddar** [comment]
@SharkeyPaul ,

Thank you for sharing. If I've done something to contribute I apologize. 

I truly want to understand your perspective and welcome the opportunity to discuss more.

Let me know.

Damon

**Comment by DMSuit** [comment]
@dstoddar and @SharkeyPaul 

I appreciate the graph and information on 'psychological safety.'  Is there no way to make the team assessment anonymous but still allow the team feedback for the retrospective to show who submitted it?  It is difficult to get clarity on a retrospective if the feedback does not provide a direction for open discussion to resolve, celebrate, or act.  Additionally, if that is such a concern on a retro, perhaps consideration of a user making their feedback anonymous based on what they are entering rather than all or nothing might be an option.

I really believe if a person feels that unsafe, the issue is bigger than submitting retro feedback with a name on it.

**Pull request merged**
