### PR TITLE
Changing to codecov for codecoverage

### PR DESCRIPTION
**Pull request by mindlessroman**
# Pull Request

Relevant Issue(s): #455 

## Description

To decentralize how code coverage is reported.

## Bug or Feature?

- [x] Bug fix
- [x] New feature

## Fundamentals

- [x] I have read the [**CONTRIBUTING**](https://github.com/microsoft/vsts-extension-retrospectives/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] I have updated any relevant documentation accordingly.
- [x] I have included an update blurb (50 words or less) at the top of `CHANGELOG.md`,
    to be included with the next release.
  - [x] I have included a link to this PR in that blurb.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

## Accessibility

- [ ] I have tested my changes on both light and dark themes.
- [ ] I have tested my changes on both mobile and desktop views, when needed.
- [ ] I have included image descriptions and aria-labels where I can.

## Screenshots and Logs

Now comments on PRs will come from codecov!

Image showing a comment generated by Codecov, showing the coverage diff based on changes in this PR

### CODE REVIEW

**Comment by mindlessroman** [comment]
Temporarily publishing this to see if codecov picks up.

**Comment by mindlessroman** [comment]
In CHANGELOG.md:
```text
## v1.90.X 

* Github Experience: Updating README to include the code coverage and status badges.
Github PRs now get code coverage comments from CodeCov.
From [Github PR #461](https://github.com/microsoft/vsts-extension-retrospectives/pull/461).
```

This release number will need to be added when we next release.

**Comment by mindlessroman** [comment]
Image showing the status badges for Codecov, CI Frontend, CI Backend, and CD Frontend at the top of the README page

And what the status badges look like!

**Review by polatengin — APPROVED** [review]
perfect! thanks..

**Pull request merged**
